apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/pulp-operator.pulp: ""
  name: pulp-operator
  namespace: platform-stream
spec:
  channel: beta
  installPlanApproval: Automatic
  name: pulp-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: pulp-operator.v1.0.0-alpha.4
